version: "3.9"
networks:
  easymove: 
    external: true

services:
  database:
    build: ./bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'
    ports:
      - "5433:5432"
    networks:
      - easymove
    container_name: database_server

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - easymove
    container_name: backend_server
  
  frontend:
    build: ./frontend/easymove
    ports:
      - "80:5173"
    networks:
      - easymove
    container_name: frontend_server